version: '3'

services:
  postgres_primary:
    image: postgres
    container_name: postgres_primary
    restart: always
    volumes:
      - ./primary_data:/var/lib/postgresql/data
      - ./init/init.sh:/docker-entrypoint-initdb.d/init.sh
    environment:
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data
      - PGUSER=postgres
      - POSTGRES_REPLICATION_USER=replicator
      - POSTGRES_REPLICATION_PASSWORD=replicator_password
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - primary_network
      - shared_network
    ports:
      - "5432:5432"

networks:
  primary_network:
    name: primary_network
  shared_network:
    name: shared_network
